version: '3.2'

services:
  snort:
    build:
      context: ./
      args:
        PROTECTED_SUBNET: "${PROTECTED_SUBNET}"
        EXTERNAL_SUBNET: "${EXTERNAL_SUBNET}"
        OINKCODE: "${OINKCODE}"
    image: mataelang/snorqttalpine-sensor:latest
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    