version: '3.2'

services:
  snort-sensor:
    image: mataelang/snorqttalpine-sensor:latest
    hostname: snorqtt-sensor
    container_name: snorqtt-sensor
    network_mode: host
    env_file:
      - ./.env
    ports:
      - "5000:5000"
