version: '3.2'

volumes:
  mqtt_data:

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    hostname: mqtt-broker
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - type: bind
        source: ./mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
      - type: volume
        source: mqtt_data
        target: /mosquitto/data
        volume:
          nocopy: true
      - type: bind
        source: ./mosquitto.log
        target: /mosquitto/log/mosquitto.log

  snorqtt-sensor:
    build:
      context: ./
      args:
        PROTECTED_SUBNET: "${PROTECTED_SUBNET}"
        EXTERNAL_SUBNET: "${EXTERNAL_SUBNET}"
        OINKCODE: "${OINKCODE}"
    # image: mataelang/snorqttalpine-sensor:latest
    hostname: snorqtt-sensor
    container_name: snorqtt-sensor
    env_file:
      - ./.env
    ports:
      - "5000:5000"
