version: '3.2'

volumes:
  - mqtt_data:

services:
  snorqtt-sensor:
    build:
      context: ./
      args:
        PROTECTED_SUBNET: "${PROTECTED_SUBNET}"
        EXTERNAL_SUBNET: "${EXTERNAL_SUBNET}"
        OINKCODE: "${OINKCODE}"
    # image: mataelang/snorqttalpine-sensor:latest
    env_file:
      - ./.env
    ports:
      - "5000:5000"
  
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto.conf:/mosquitto/config/mosquitto.conf
      - type: volume
        source: mqtt_data
        target: /mosquitto/data
        volume:
          nocopy: true
      - type: bind
        source: /var/log/mqtt_broker/mosquitto.log
        target: /mosquitto/log/mosquitto.log
