version: '3.2'

services:
  snort:
    build:
      context: ./
      args:
        PROTECTED_SUBNET: "172.17.0.0/16"
        EXTERNAL_SUBNET: "any"
        OINKCODE: "${OINKCODE}"
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    